@Media_Api_HostAddress = http://localhost:5255/api/books

GET {{Media_Api_HostAddress}}/
Accept: application/json

###
POST {{Media_Api_HostAddress}}
Accept: application/json
Content-type: application/json

{
  "title": "Sagan om ringen",
  "author": "J.R.R Tolkein",
  "pages": 623
}


###
DELETE {{Media_Api_HostAddress}}/1
Accept: application/json